#Specify location of assembler
CC = "C:\Program Files (x86)\Pasmo\pasmo"	
#Source filename	
FILENAME = CPM_BL
#Mode
MODE = --bin

BOOTSTRAP:	$(FILENAME).asm
	$(CC) $(MODE) $(FILENAME).asm $(FILENAME).bin